repos:
-   repo: https://github.com/ambv/black
    rev: "22.10.0"
    hooks:
    - id: black
      language_version: python3.11
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.4.0
    hooks:
      - id: fix-encoding-pragma
      - id: trailing-whitespace
      - id: requirements-txt-fixer
      - id: detect-private-key
      - id: check-merge-conflict
      # - id:

# -   repo: https://github.com/Kludex/bump-testclient
#     rev: 0.3.0
#     hooks:
#       - id: bump_testclient


# -   repo: git://github.com/doublify/pre-commit-isort
#     sha: master
#     hooks:
#     -   id: isort

      # - id: flake8
# -   repo: https://github.com/pre-commit/mirrors-isort
#     rev: 'v4.3.21'  # Use the revision sha / tag you want to point at
#     hooks:
#     -   id: isort