FROM python:3.7-slim-buster
RUN apt-get update && apt-get -y install gcc
MAINTAINER Mike Ryan "mikeryan56@gmail.com"
EXPOSE 5000
COPY . /app
WORKDIR /app
# ENV Variables
# Application information
ENV APP_VERSION='20.03.08'
ENV OWNER='Your Name'
ENV WEBSITE='https://your.domain.com/support'
# Demo settings
ENV CREATE_SAMPLE_DATA=True
ENV NUMBER_TASKS=1000
ENV NUMBER_USERS=1000
# Cofigurations
ENV HOST_DOMAIN='https://your.domain.com'
#prd for production or 'dev' for development
ENV RELEASE_ENV='dev'
ENV SQLALCHEMY_DATABASE_URI='sqlite:///sqlite_db/api.db'
ENV SECRET_KEY='JMA14aye00GHXsfoPU3TfaEqFI0y809BvjkZjL5NIzbK8PtBjFqxiJv4orZdGOBJ'
ENV ALGORITHM="HS256"
ENV ACCESS_TOKEN_EXPIRE_MINUTES=10080
# Loguru settings
ENV LOGURU_RETENTION='10 days'
ENV LOGURU_ROTATION='100 MB'
ENV LOGURU_LOGGING_LEVEL='INFO'
# Leave intact for license
ENV CREATED_BY='Mike Ryan'
ENV LICENSE_TYPE='MIT'
ENV LICENSE_LINK='https://github.com/devsetgo/test-api/blob/master/LICENSE'

RUN pip install -r requirements.txt
CMD ["gunicorn",  "-c", "gunicorn_cfg.py", "main:app"]