FROM python:3.7-alpine
RUN apk add --no-cache --virtual .pynacl_deps build-base python3-dev libffi-dev
MAINTAINER Mike Ryan "mikeryan56@gmail.com"
EXPOSE 5000
ENV VIRTUAL_HOST test-api.devsetgo.com
ENV LETSENCRYPT_HOST test-api.devsetgo.com
COPY . /app
WORKDIR /app
RUN pip install -r requirements.txt
# CMD ["uvicorn", "main:app", "--workers", "4", "--port", "5000", "--log-level=info"]
CMD [ "hypercorn","main:app","--workers","4","-b","0.0.0.0:5000","--access-log", " - "]